import { useEffect, useState } from "react";
import type { ExtractedStyles, FontFamily } from "../types";
import Header from "./components/Header";
import ColorPalette from "./components/ColorPalette";
import AllColors from "./components/AllColors";
import ColorTokens from "./components/ColorTokens";
import Typography from "./components/Typography";
import Buttons from "./components/Buttons";
import Links from "./components/Links";
import Spacing from "./components/Spacing";
import BorderRadius from "./components/BorderRadius";
import Shadows from "./components/Shadows";
import ExportButton from "./components/ExportButton";

export default function App() {
  const [data, setData] = useState<ExtractedStyles | null>(null);
  const [error, setError] = useState<string | null>(null);

  useEffect(() => {
    chrome.storage.session
      .get("stylebookData")
      .then((result) => {
        if (result.stylebookData) {
          setData(result.stylebookData as ExtractedStyles);
          injectGoogleFonts(result.stylebookData.fonts);
        } else {
          setError(
            "No style data found. Right-click a page and choose 'Extract styles from this page'.",
          );
        }
      })
      .catch(() => {
        setError("Failed to load style data.");
      });
  }, []);

  if (error) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-gray-500 text-lg">{error}</p>
      </div>
    );
  }

  if (!data) {
    return (
      <div className="min-h-screen flex items-center justify-center">
        <p className="text-gray-500 text-lg animate-pulse">
          Loading style book…
        </p>
      </div>
    );
  }

  const stats = {
    colorCount: data.colors.all.length,
    tokenCount: data.colorTokens.length,
    fontCount: data.fonts.length,
    typographyCount: data.typography.length,
    buttonCount: data.buttons.length,
    shadowCount: data.shadows.length,
  };

  return (
    <div className="max-w-5xl mx-auto px-6 py-10 space-y-10">
      <div className="flex items-start justify-between no-print">
        <div />
        <ExportButton data={data} />
      </div>

      <Header site={data.site} fonts={data.fonts} stats={stats} />

      <ColorPalette colors={data.colors.curated} />
      <AllColors colors={data.colors.all} />
      <ColorTokens tokens={data.colorTokens} />
      <Typography typography={data.typography} />

      {/* Buttons + Links share a page */}
      <div className="print-break-before print-group space-y-10">
        <Buttons buttons={data.buttons} noPageBreak />
        <Links links={data.links} noPageBreak />
      </div>

      {/* Spacing + Border Radius + Shadows share a page */}
      <div className="print-break-before print-group space-y-10">
        <Spacing spacing={data.spacing} noPageBreak />
        <BorderRadius borderRadius={data.borderRadius} noPageBreak />
        <Shadows shadows={data.shadows} noPageBreak />
      </div>

      {/* Print footer */}
      <footer className="hidden print:block text-center text-xs text-gray-400 pt-4 border-t border-gray-200">
        Generated by BacktraceDesign &middot; {data.site.url}
      </footer>
    </div>
  );
}

function injectGoogleFonts(fonts: FontFamily[]) {
  const googleUrls = new Set(
    fonts
      .filter((f) => f.source === "google" && f.googleUrl)
      .map((f) => f.googleUrl!),
  );
  for (const url of googleUrls) {
    if (!document.querySelector(`link[href="${url}"]`)) {
      const link = document.createElement("link");
      link.rel = "stylesheet";
      link.href = url;
      document.head.appendChild(link);
    }
  }
}
