import type { ExtractedStyles } from "../../types";
import { formatVarName } from "../../utils/colorUtils";

/**
 * Export a tailwind.config.js snippet with theme.extend values
 * derived from the extracted styles.
 */
export function exportTailwindConfig(data: ExtractedStyles): string {
  const colors = buildColors(data);
  const fontFamily = buildFontFamily(data);
  const fontSize = buildFontSize(data);
  const spacing = buildSpacing(data);
  const borderRadius = buildBorderRadius(data);
  const boxShadow = buildBoxShadow(data);

  const extend: Record<string, unknown> = {};
  if (Object.keys(colors).length) extend.colors = colors;
  if (Object.keys(fontFamily).length) extend.fontFamily = fontFamily;
  if (Object.keys(fontSize).length) extend.fontSize = fontSize;
  if (Object.keys(spacing).length) extend.spacing = spacing;
  if (Object.keys(borderRadius).length) extend.borderRadius = borderRadius;
  if (Object.keys(boxShadow).length) extend.boxShadow = boxShadow;

  const config = {
    theme: { extend },
  };

  const lines = [
    `// Tailwind CSS theme extracted from ${data.site.title}`,
    `// Source: ${data.site.url}`,
    `// Generated by BacktraceDesign`,
    ``,
    `/** @type {import('tailwindcss').Config} */`,
    `export default ${JSON.stringify(config, null, 2)};`,
  ];

  return lines.join("\n");
}

function buildColors(data: ExtractedStyles) {
  const colors: Record<string, string> = {};
  for (const c of data.colors.all) {
    const name = c.varNames.length > 0
      ? slugify(formatVarName(c.varNames[0]))
      : c.hex.replace("#", "");
    colors[name] = c.hex;
  }
  return colors;
}

function buildFontFamily(data: ExtractedStyles) {
  const seen = new Set<string>();
  const families: Record<string, string[]> = {};
  for (const t of data.typography) {
    const primary = t.fontFamily.split(",")[0].trim().replace(/['"]/g, "");
    if (seen.has(primary)) continue;
    seen.add(primary);
    const key = slugify(primary);
    families[key] = t.fontFamily.split(",").map((f) => f.trim().replace(/['"]/g, ""));
  }
  return families;
}

function buildFontSize(data: ExtractedStyles) {
  const sizes: Record<string, [string, { lineHeight: string }]> = {};
  for (const t of data.typography) {
    const key = slugify(t.label);
    sizes[key] = [t.fontSize, { lineHeight: t.lineHeight }];
  }
  return sizes;
}

function buildSpacing(data: ExtractedStyles) {
  const spacing: Record<string, string> = {};
  for (const s of data.spacing) {
    const key = Number.isInteger(s.px) ? String(s.px) : String(s.px).replace(".", "-");
    spacing[key] = s.value;
  }
  return spacing;
}

function buildBorderRadius(data: ExtractedStyles) {
  const radii: Record<string, string> = {};
  for (let i = 0; i < data.borderRadius.length; i++) {
    const r = data.borderRadius[i];
    const key = r.varName ? slugify(formatVarName(r.varName)) : `r${i + 1}`;
    radii[key] = r.value;
  }
  return radii;
}

function buildBoxShadow(data: ExtractedStyles) {
  const shadows: Record<string, string> = {};
  for (let i = 0; i < data.shadows.length; i++) {
    const s = data.shadows[i];
    const key = s.varName ? slugify(formatVarName(s.varName)) : `shadow-${i + 1}`;
    shadows[key] = s.value;
  }
  return shadows;
}

function slugify(name: string): string {
  return name.toLowerCase().replace(/\s+/g, "-").replace(/[^a-z0-9-]/g, "");
}
